import turtle as t
t.speed(0)
t.color('red')
t.begin_fill()
t.forward(300)
t.right(90)
t.forward(200)
t.right(90)
t.forward(300)
t.right(90)
t.forward(200)
t.right(90)
t.end_fill()
t.color('yellow')
t.penup()
t.goto(34,-43)
t.pendown()
t.begin_fill()
for i in range(5):
    t.forward(64)
    t.right(144)
t.end_fill()
t.penup()
t.goto(121,-25)
t.pendown()
t.begin_fill()
for i in range(5):
    t.forward(33)
    t.right(144)
t.end_fill()
t.penup()
t.goto(112,-67)
t.pendown()
t.begin_fill()
for i in range(5):
    t.forward(33)
    t.right(144)
t.end_fill()
t.penup()
t.goto(87,-105)
t.pendown()
t.begin_fill()
for i in range(5):
    t.forward(33)
    t.right(144)
t.end_fill()
t.penup()
t.goto(41,-120)
t.pendown()
t.begin_fill()
for i in range(5):
    t.forward(33)
    t.right(144)
t.end_fill()
t.penup()
t.hideturtle()
t.done()